### ISSUE TITLE
Unexpected ReflectiveOperationException occurred (Gson 2.10.1).

### ISSUE THREAD

**Issue by bierdosenhalter** [zeroBzeroT/AntiIllegals#99]
```
java.lang.RuntimeException: Unexpected ReflectiveOperationException occurred (Gson 2.10.1). To support Java records, reflection is utilized to read out information about records. All these invocations happens after it is established that records exist in the JVM. This exception is unexpected behavior.
	at com.google.gson.internal.reflect.ReflectionHelper.createExceptionForRecordReflectionException(ReflectionHelper.java:162) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.reflect.ReflectionHelper.access$300(ReflectionHelper.java:10) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper.getAccessor(ReflectionHelper.java:244) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.reflect.ReflectionHelper.getAccessor(ReflectionHelper.java:144) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:266) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:125) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:55) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:368) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:368) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.toJson(Gson.java:842) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:712) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:689) ~[gson-2.10.1.jar:?]
	at org.zeroBzeroT.antiillegals.result.CachedState.nbtHashCode(CachedState.java:53) ~[?:?]
	at org.zeroBzeroT.antiillegals.result.CachedState.itemStackHashCode(CachedState.java:27) ~[?:?]
	at org.zeroBzeroT.antiillegals.helpers.RevertHelper.checkItemStack(RevertHelper.java:299) ~[?:?]
	at org.zeroBzeroT.antiillegals.helpers.RevertHelper.revert(RevertHelper.java:57) ~[?:?]
	at org.zeroBzeroT.antiillegals.helpers.RevertHelper.lambda$revertAll$1(RevertHelper.java:148) ~[?:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1034) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
	at org.zeroBzeroT.antiillegals.helpers.RevertHelper.revertAll(RevertHelper.java:148) ~[?:?]
	at org.zeroBzeroT.antiillegals.helpers.RevertHelper.revertAll(RevertHelper.java:95) ~[?:?]
	at org.zeroBzeroT.antiillegals.Events.onInventoryClick(Events.java:166) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor44.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-491]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-491]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-491]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3119) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:25) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-491]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-491]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoSuchMethodException: net.minecraft.world.item.armortrim.TrimMaterial.f()
	at java.lang.Class.getMethod(Class.java:2395) ~[?:?]
	at com.google.gson.internal.reflect.ReflectionHelper$RecordSupportedHelper.getAccessor(ReflectionHelper.java:242) ~[gson-2.10.1.jar:?]
	... 59 more
```

**Comment by bierdosenhalter** [comment]
solved with new caching
